Repository BetterCrypto/Applied-Crypto-Hardening, pull requests merged in 2018-12, with the labels that each got.

#163 Create LICENSE
  LICENSE
Labels: license

#173 ci: Build asciidoc using asciidoctor(-pdf) and upload build artifacts (#160)
  .travis.yml
  Gemfile
  Gemfile.lock
  tools/ci/copy-build.sh
  tools/ci/id_rsa.aes-256-cbc.enc
  tools/ci/known_hosts
Labels: enhancement

#284 Fix spelling/case of "AsciiDoc"
  src/applied-crypto-hardening.adoc
Labels: bug

#300 Logo fixes
  src/applied-crypto-hardening.adoc
  src/assets/images/logo.png
  src/assets/images/logo.svg
Labels: bug
